<li >
            <div class="img">
              <div class="i_img"> <a href="[field:arcurl/]"> <img src="[field:picname/]" width="290" height="211" class="juzhongimg"/> </a> <span class="juzhongspan"></span> </div>
            </div>
            <div class="i_title"> <a href="">[field:title/]</a> </div>
            <div class="acctime">[field:pubdate function="GetDateTimeMK(@me)" /]</div>
            <div class="bd"> [field:infos/]... </div>
          </li>