<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:dq itemname="地区" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="亚洲,欧洲,美洲"  maxlength="250" page="">
</field:dq>
<field:leixing itemname="类型" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="私人制定,跟团游,自由行,蜜月"  maxlength="250" page="">
</field:leixing>
