<div class="d_1">
          <div class="d1_img"><a href="[field:arcurl/]"><img src="[field:picname/]" width="485" height="280" class="juzhongimg"/></a><span class="juzhongspan"></span></div>
          <div class="d1_title"><a href="[field:arcurl/]">[field:title /]</a></div>
          <div class="d1_acctime">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
          <div class="d1_bife"> [field:infos/]... </div>
        </div>