<li>
            <div class="fx_1"> <a href="[field:arcurl/]"><img src="[field:picname/]" width="100%" /></a> <a href="[field:arcurl/]">
              <div class="ddd">
                <div class="titles">[field:title /]</div>
                <div class="acctime">[field:pubdate function="MyDate('d/m/Y',@me)"/]</div>
                <div class="info_disc"></div>
              </div>
              </a> </div>
          </li>