<?php
$z[0]=Array("global","",622,648);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",692,722);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",759,786);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1300,1335);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n    <li>\r\n      <div class=\"pro_11\"> <img src=\"[field:picname/]\" width=\"100%\" /> <a href=\"[field:arcurl /]\">\r\n        <div class=\"tt\">\r\n          <div class=\"titles\">[field:title /]</div>\r\n        </div>\r\n        </a> </div>\r\n    </li>\r\n    ",3769,4075);
$z[4][4]['row']="16";
$z[4][4]['typeid']="2";
$z[4][4]['titlelen']="10";
$z[5]=Array("type","\r\n      <div class=\"sl_1\">[field:typename /]</div>\r\n      ",5677,5769);
$z[5][4]['typeid']="3";
$z[6]=Array("arclist","\r\n          <li>\r\n            <div class=\"fx_1\"> <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"100%\" /></a> <a href=\"[field:arcurl/]\">\r\n              <div class=\"ddd\">\r\n                <div class=\"titles\">[field:title /]</div>\r\n                <div class=\"acctime\">[field:pubdate function=\"MyDate('d/m/Y',@me)\"/]</div>\r\n                <div class=\"info_disc\"></div>\r\n              </div>\r\n              </a> </div>\r\n          </li>\r\n          ",6137,6643);
$z[6][4]['typeid']="3";
$z[6][4]['row']="6";
$z[7]=Array("type","\r\n      <div class=\"a_1\">[field:typename /]</div>\r\n      ",7062,7153);
$z[7][4]['typeid']="1";
$z[8]=Array("type","<span class=\"news_cn_title\">[field:typename /]</span>",9480,9567);
$z[8][4]['typeid']="4";
$z[9]=Array("arclist","\r\n        <div class=\"d_1\">\r\n          <div class=\"d1_img\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"485\" height=\"280\" class=\"juzhongimg\"/></a><span class=\"juzhongspan\"></span></div>\r\n          <div class=\"d1_title\"><a href=\"[field:arcurl/]\">[field:title /]</a></div>\r\n          <div class=\"d1_acctime\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</div>\r\n          <div class=\"d1_bife\"> [field:infos/]... </div>\r\n        </div>\r\n        ",9659,10184);
$z[9][4]['typeid']="4";
$z[9][4]['row']="1";
$z[9][4]['orderby']="pubdate";
$z[10]=Array("arclist","\r\n            <li>\r\n              <div class=\"d2_img\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"230\" height=\"169\"/></a></div>\r\n              <div class=\"d2_title\"><a href=\"/info-detail.php?InfoId=79\">[field:title /]</a></div>\r\n              <div class=\"d2_acctime\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</div>\r\n            </li>\r\n            ",10241,10691);
$z[10][4]['typeid']="4";
$z[10][4]['row']="4";
$z[10][4]['titlelen']="20";
$z[10][4]['orderby']="pubdate";
$z[11]=Array("global","",14307,14333);
$z[11][4]['name']="cfg_powerby";
$z[12]=Array("global","",14335,14359);
$z[12][4]['name']="cfg_beian";

?>