<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",918,953);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1051,1073);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n          <li >\r\n            <div class=\"img\">\r\n              <div class=\"i_img\"> <a href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\" width=\"290\" height=\"211\" class=\"juzhongimg\"/> </a> <span class=\"juzhongspan\"></span> </div>\r\n            </div>\r\n            <div class=\"i_title\"> <a href=\"\">[field:title/]</a> </div>\r\n            <div class=\"acctime\">[field:pubdate function=\"GetDateTimeMK(@me)\" /]</div>\r\n            <div class=\"bd\"> [field:infos/]... </div>\r\n          </li>\r\n          ",1240,1798);
$z[6][4]['pagesize']="9";
$z[6][4]['titlelen']="30";
$z[6][4]['infolen']="180";
$z[7]=Array("pagelist","",2013,2069);
$z[7][4]['listitem']="pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2121,2158);
$z[8][4]['filename']="footer.htm";

?>