<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",918,953);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1047,1069);
$z[5][4]['name']="typename";
$z[6]=Array("php"," AddFilter(2,1,'dq'); ",1210,1253);
$z[7]=Array("php"," AddFilter(2,1,'leixing'); ",1334,1382);
$z[8]=Array("list","\r\n          <li >\r\n            <div class=\"pim\">\r\n              <div class=\"pimg\"> <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" class=\"juzhongimg\" style=\"width:291px; height:291px;\"/></a><span class=\"juzhongspan\"></span> </div>\r\n            </div>\r\n            <div class=\"pro_name\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n          </li>\r\n          ",2383,2805);
$z[8][4]['pagesize']="9";
$z[8][4]['titlelen']="30";
$z[9]=Array("pagelist","",2923,2979);
$z[9][4]['listitem']="pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",3031,3068);
$z[10][4]['filename']="footer.htm";

?>