<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",916,951);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n          <li >\r\n            <div class=\"i_1\">\r\n              <div class=\"pim\"> <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" class=\"juzhongimg\" /></a><span class=\"juzhongspan\"></span> </div>\r\n            </div>\r\n            <div class=\"inst_title\"> <a href=\"[field:arcurl/]\"> [field:title/] </a> </div>\r\n          </li>\r\n          ",1230,1622);
$z[5][4]['pagesize']="8";
$z[5][4]['titlelen']="30";
$z[6]=Array("pagelist","",1785,1841);
$z[6][4]['listitem']="pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",1893,1930);
$z[7][4]['filename']="footer.htm";

?>